using System.Collections.Generic;
// ReSharper disable StringLiteralTypo

namespace IncrementalLib
{
  /// <summary>
  /// Class containing all the constants used in the IncrementalLib
  /// </summary>
  public static class Constants
  {
    /// <summary>
    /// Dictionary containing all the units up to 1e333
    /// </summary>
    public static readonly Dictionary<int, Unit> units = new Dictionary<int, Unit>
          {
            { 0, new Unit("", "")},
            { 3, new Unit("Thousand", "k")},
            { 6, new Unit("Million", "m")},
            { 9, new Unit("Billion", "b")},
            { 12, new Unit("Trillion", "t")},
            { 15, new Unit("Quadrillion", "q")},
            { 18, new Unit("Quintillion", "Q")},
            { 21, new Unit("Sextillion", "s")},
            { 24, new Unit("Septillion", "S")},
            { 27, new Unit("Octillion", "o")},
            { 30, new Unit("Nonillion", "n")},
            { 33, new Unit("Decillion", "d")},
            { 36, new Unit("Undecillion", "ud")},
            { 39, new Unit("Duodecillion", "dd")},
            { 42, new Unit("Tredecillion", "td")},
            { 45, new Unit("Quattuordecillion", "qd")},
            { 48, new Unit("Quindecillion", "Qd")},
            { 51, new Unit("Sexdecillion", "sd")},
            { 54, new Unit("Septendecillion", "Sd")},
            { 57, new Unit("Octodecillion", "od")},
            { 60, new Unit("Novendecillion", "nd")},
            { 63, new Unit("Vigintillion", "v")},
            { 66, new Unit("Unvigintillion", "uv")},
            { 69, new Unit("Duovigintillion", "dv")},
            { 72, new Unit("Tresvigintillion", "tv")},
            { 75, new Unit("Quattuorvigintillion", "qv")},
            { 78, new Unit("Quinvigintillion", "Qv")},
            { 81, new Unit("Sesvigintillion", "sv")},
            { 84, new Unit("Septemvigintillion", "Sv")},
            { 87, new Unit("Octovigintillion", "ov")},
            { 90, new Unit("Novemvigintillion", "nv")},
            { 93, new Unit("Trigintillion", "T")},
            { 96, new Unit("Untrigintillion", "uT")},
            { 99, new Unit("Duotrigintillion", "dT")},
            { 102, new Unit("Trestrigintillion", "tT")},
            { 105, new Unit("Quattuortrigintillion", "qT")},
            { 108, new Unit("Quintrigintillion", "QT")},
            { 111, new Unit("Sestrigintillion", "sT")},
            { 114, new Unit("Septentrigintillion", "ST")},
            { 117, new Unit("Octotrigintillion", "oT")},
            { 120, new Unit("Noventrigintillion", "nT")},
            { 123, new Unit("Quadragintillion", "qg")},
            { 126, new Unit("Unquadragintillion", "uqg")},
            { 129, new Unit("Duoquadragintillion", "dqg")},
            { 132, new Unit("Tresquadragintillion", "tqg")},
            { 135, new Unit("Quattuorquadragintillion", "qqg")},
            { 138, new Unit("Quinquadragintillion", "Qqg")},
            { 141, new Unit("Sesquadragintillion", "sqg")},
            { 144, new Unit("Septenquadragintillion", "Sqg")},
            { 147, new Unit("Octoquadragintillion", "oqg")},
            { 150, new Unit("Novenquadragintillion", "nqg")},
            { 153, new Unit("Quinquagintillion", "Qg")},
            { 156, new Unit("Unquinquagintillion", "uQg")},
            { 159, new Unit("Duoquinquagintillion", "dQg")},
            { 162, new Unit("Tresquinquagintillion", "tQg")},
            { 165, new Unit("Quattuorquinquagintillion", "qQg")},
            { 168, new Unit("Quinquinquagintillion", "QQg")},
            { 171, new Unit("Sesquinquagintillion", "sQg")},
            { 174, new Unit("Septenquinquagintillion", "SQg")},
            { 177, new Unit("Octoquinquagintillion", "oQg")},
            { 180, new Unit("Novenquinquagintillion", "nQg")},
            { 183, new Unit("Sexagintillion", "sg")},
            { 186, new Unit("Unsexagintillion", "usg")},
            { 189, new Unit("Duosexagintillion", "dsg")},
            { 192, new Unit("Tresexagintillion", "tsg")},
            { 195, new Unit("Quattuorsexagintillion", "qsg")},
            { 198, new Unit("Quinsexagintillion", "Qsg")},
            { 201, new Unit("Sesexagintillion", "ssg")},
            { 204, new Unit("Septensexagintillion", "Ssg")},
            { 207, new Unit("Octosexagintillion", "osg")},
            { 210, new Unit("Novensexagintillion", "nsg")},
            { 213, new Unit("Septuagintillion", "Sg")},
            { 216, new Unit("Unseptuagintillion", "uSg")},
            { 219, new Unit("Duoseptuagintillion", "dSg")},
            { 222, new Unit("Treseptuagintillion", "tSg")},
            { 225, new Unit("Quattuorseptuagintillion", "qSg")},
            { 228, new Unit("Quinseptuagintillion", "QSg")},
            { 231, new Unit("Seseptuagintillion", "sSg")},
            { 234, new Unit("Septenseptuagintillion", "SSg")},
            { 237, new Unit("Octoseptuagintillion", "oSg")},
            { 240, new Unit("Novenseptuagintillion", "nSg")},
            { 243, new Unit("Octogintillion", "Og")},
            { 246, new Unit("Unoctogintillion", "uOg")},
            { 249, new Unit("Duooctogintillion", "dOg")},
            { 252, new Unit("Tresoctogintillion", "tOg")},
            { 255, new Unit("Quattuoroctogintillion", "qOg")},
            { 258, new Unit("Quinoctogintillion", "QOg")},
            { 261, new Unit("Sexoctogintillion", "sOg")},
            { 264, new Unit("Septemoctogintillion", "SOg")},
            { 267, new Unit("Octooctogintillion", "oOg")},
            { 270, new Unit("Novemoctogintillion", "nOg")},
            { 273, new Unit("Nonagintillion", "Ng")},
            { 276, new Unit("Unnonagintillion", "uNg")},
            { 279, new Unit("Duononagintillion", "dNg")},
            { 282, new Unit("Trenonagintillion", "tNg")},
            { 285, new Unit("Quattuornonagintillion", "qNg")},
            { 288, new Unit("Quinnonagintillion", "QNg")},
            { 291, new Unit("Senonagintillion", "sNg")},
            { 294, new Unit("Septenonagintillion", "SNg")},
            { 297, new Unit("Octononagintillion", "oNg")},
            { 300, new Unit("Novenonagintillion", "nNg")},
            { 303, new Unit("Centillion", "C")},
            { 306, new Unit("Uncentillion", "uC")},
            { 309, new Unit("Duocentillion", "dC")},
            { 312, new Unit("Trescentillion", "tC")},
            { 315, new Unit("Quattuorcentillion", "qC")},
            { 318, new Unit("Quincentillion", "QC")},
            { 321, new Unit("Sexcentillion", "sC")},
            { 324, new Unit("Septencentillion", "SC")},
            { 327, new Unit("Octocentillion", "oC")},
            { 330, new Unit("Novencentillion", "nC")},
            { 333, new Unit("Decicentillion", "DC")}
          };
  }
}